# Generated by Django 4.0.4 on 2022-05-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_postmodel_comment_text_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='post_obj',
        ),
    ]
